#!/bin/sh /etc/rc.common
# Copyright (C) 2016 Onion Corporation
START=99

USE_PROCD=1
BIN="/usr/bin/node --max-old-space-size=128 /usr/bin/onion-node-red/node_modules/node-red/red.js --userDir /root/.node-red"
OPT=""

start_service() {
        procd_open_instance
        procd_set_param command $BIN $OPT
        procd_set_param respawn
        procd_close_instance
}


